name: 'Automatic build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  continuous-delivery:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
      - uses: actions/checkout@main

      - name: Install tools
        run: |
          python3 --version
          sudo apt install python3-pip -y
