# name: Node js build test
# on:                                  # Event 감지
#   push:
#     branches:
#       - main
# jobs:                                # Job 설정
#   build:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout source code.   # Repo checkout
#         uses: actions/checkout@main

#       - name: Check Node v            # Node v 확인
#         run: node -v

#       - name: Repo check
#         run: tree

#       - name: Install Dependencies    # 의존 파일 설치
#         run: npm install

#       - name: Build                   # React Build
#         run: npm run build

#       - name: Deploy
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{secrets.GITHUB_TOKEN}}
#           PUBLISH_BRANCH: gh-pages
#           publish_dir: ./build
