name: 'Bentoml Build'
on:
  push:
    branches:
      - main
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@main

      - name: Repo check
        run: tree -L 3
      - name: Install tools
        run:
          python3 --version
          sudo apt install python3-pip -y

      - name: Install requrements
        run:
          pip3 install -r requirements.txt

      - name: bentoml packing
        run:
          python3 bento-packing.py True

      - name: bentoml serve test
        run:
          bentoml get api_service:latest --print-location --quiet